# Generated by Django 4.1.5 on 2023-01-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
